import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const AsideBar = dynamic(() => import('../components/AsideBar'), {
  ssr: false,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='flex h-screen'>
        <AsideBar />

        <main className='flex-1'>{children}</main>
      </body>
    </html>
  )
}
